# Generated by Django 4.0.4 on 2022-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0002_saleproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_actual_price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount_price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
