# Generated by Django 4.0.4 on 2022-04-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0005_alter_saleproduct_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
