# Generated by Django 4.0.4 on 2022-04-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0010_alter_cart_added_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
