# Generated by Django 4.0.4 on 2022-04-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0012_alter_cart_product_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
