# Generated by Django 4.0.4 on 2022-04-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0013_remove_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(default='value'),
        ),
    ]
