# Generated by Django 4.0.4 on 2022-04-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0014_cart_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='slug',
        ),
    ]
