# Generated by Django 4.0.4 on 2022-04-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0016_alter_cart_product_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_added', to='granite.product'),
        ),
    ]
