# Generated by Django 4.0.4 on 2022-04-22 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0017_alter_cart_product_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_addded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
