# Generated by Django 4.0.4 on 2022-04-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0018_product_date_addded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_addded',
            new_name='date_added',
        ),
    ]
