# Generated by Django 4.0.4 on 2022-04-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granite', '0019_rename_date_addded_product_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
    ]
